### ISSUE TITLE
IPs

### ISSUE THREAD

**Issue by Philmod** [Shrugs/skiff#10]
Hey,

Is there a way to get the droplet's ip?

Thanks,
Philmod

**Comment by Shrugs** [comment]
On a droplet, the ip address is the network's `ip_address` property.

for example:

```python
my_droplet = s.Droplet.get('my droplet name')
# select the first ipv4 network's address
# you also have access to ipv6 networks with `v6`
ip_addr = my_droplet.networks['v4'][0]['ip_address']

```

**Comment by Philmod** [comment]
I've realized that just after my message. Sorry about that.
Great tool!

**Comment by Shrugs** [comment]
No worries, thanks!
